[project]
name = "ft_package"
version = "0.0.1"
authors = [
	{ name = "Eagle" },
	{ email = "eagle@42.fr" },
]
description = "A sample test package"
readme = "README.md"
license = { text = "MIT" } # Deprecated but pip show only catch this
